version: '2'
services:
  targeter-server:
    build: .
    ports:
      - "80:8080"
    networks:
      targeterserverntw: {}
    command: java -jar -Dspring.profiles.active=prod TargeterServer.jar
networks:
  targeterserverntw:
    driver: bridge
