version: '2'
services:
  targeter-server:
    build: .
    ports:
      - "80:8080"
    networks:
      targeterserverntw: {}
    command: java -jar TargeterServer.jar
  targeter-dotnet:
    build: ./motivator
    ports:
      - "9000:8080"
    networks:
      targeterserverntw: {}
networks:
  targeterserverntw:
    driver: bridge
